### ISSUE TITLE
Printing support

### ISSUE THREAD

**Issue by mase76** [PrivacyApps/document-viewer#112]
Please add printing support over Android's printing subsystem.

**Comment by frazzmark** [comment]
:+1:

**Comment by KrasnayaPloshchad** [comment]
That would be useful if some people want to print via certain ways as ePrint.

**Comment by Dionis0s** [comment]
I want to push this feature! It would be nice!!

**Comment by DJCrashdummy** [comment]
i guess this can be closed as it is a duplicate of #146.
