### ISSUE TITLE
CJK support

### ISSUE THREAD

**Issue by abderrahim** [PrivacyApps/document-viewer#115]
Looks like this is due to the size of the APK (#88), but now with #99 merged, the size seems reasonable, and we can reintroduce CJK support.

One thing I noticed is there is middle ground between using -DNOCJK and not using it: we could use -DNOCJKFONT. This way, support for CJK is included but not the fallback font (DroidSansFallback, which should be available on all android devices anyway).

I did some measurements and removing -DNOCJK adds 3.5M to the APK, and replacing -DNOCJK by -DNOCJKFONT adds only 1.1M, and pdf with embedded fonts work.

It would be nice to patch mupdf to use the DroidSansFallback from the device, but for now compiling with -DNOCJKFONT would be an easy solution for most cases.

What do you think ?

**Comment by tuxor1337** [comment]
I think that we should take into consideration, that currently none of our distribution channels uses the splitted APKs. Especially on f-droid there's a problem of implementation: https://f-droid.org/forums/topic/how-to-use-separate-apks-for-each-abi-in-f-droid/ So for now, the APK is still about 10 MB in size and adding -DNOCJKFONT would add another 3 or 4 MB.

**Comment by FrankEular** [comment]
I found a CJK pdf file which failed to display in Document Viewer but displayed well in MuPDF. I base64 it and uploaded as http://paste2.org/VhmPyGp7

**Comment by abderrahim** [comment]
Actually adding -DNOCJKFONT adds 5M to the APK. Would that be acceptable ? (If so, I'll also add code to use DroidSansFallback from the device)

@FrankEular: If the pdf displays fine with 2.7, then we're aware of the problem. If not, please file a new bug.

**Comment by tuxor1337** [comment]
I don't know what's acceptable. We originally added the -DNOCJK option because somebody complained about 24 MB being too large. Before that, we had appx. 9 MB. For me, even 24 MB would be fine.

**Comment by KrasnayaPloshchad** [comment]
I found libebookdroid.so in the main DV package was embeded Nimbus fonts, which is also included in DV Font Pack. These fonts should also be excluded in the main package to reduce the size, replaced by invoking corresponding system fonts.

**Comment by ericwa** [comment]
> Actually adding -DNOCJKFONT adds 5M to the APK. Would that be acceptable ? (If so, I'll also add code to use DroidSansFallback from the device)

So, just load `/system/fonts/DroidSansFallback.ttf`? Makes sense.

> I found libebookdroid.so in the main DV 2.7.3 package was embeded Nimbus fonts, they are already included in DV Font Pack. These fonts should also be excluded in the main package to reduce the size, replaced by adding codes to invoke corresponding system fonts.

These ones? http://git.ghostscript.com/?p=mupdf.git;a=tree;f=resources/fonts/urw  I believe those are the "pdf core fonts" that every PDF reader needs, so they probably need to stay in the main package.

**Comment by KrasnayaPloshchad** [comment]
> These ones? http://git.ghostscript.com/?p=mupdf.git;a=tree;f=resources/fonts/urw I believe those are the "pdf core fonts" that every PDF reader needs, so they probably need to stay in the main package.

I remember old version of DV seems not including Nimbus fonts in the main package, using system fonts as Droid Serif, Roboto instead.

**Comment by abderrahim** [comment]
>> Actually adding -DNOCJKFONT adds 5M to the APK. Would that be acceptable ? (If so, I'll also add code to use DroidSansFallback from the device)
>
> So, just load /system/fonts/DroidSansFallback.ttf? Makes sense.

I've tried this, but forgot to report the results. Actually, the version included in android doesn't always include the vertical text variants (I believe they are only available since Lollipop), and even when included, they seem to be accessed differently from the version bundled with mupdf.

So a "quick" fix will make it work with horizontal text, but vertical text will still have wrong punctuation marks. A more involved patch will make it work correctly but only on Lollipop and newer.

I've also noticed that the APK is now 3.7 MB on f-droid, so adding the font back is also possible.

Which of these solutions seems best to you?

**Comment by tuxor1337** [comment]
Yes, since f-droid finally uses the splitted APKs we could simply forget about the CJK flag at all. Okay, the APKs would double in size (from appx. 4 to 8 MB). But I think that any size below 10 MB should be fine.

**Comment by KrasnayaPloshchad** [comment]
> I remember old version of DV seems not including Nimbus fonts in the main package, using system fonts as Droid Serif, Roboto instead.

> So, just load /system/fonts/DroidSansFallback.ttf? Makes sense.

This means DV should using fallback machanism to use these system fonts instead of Nimbus fonts to read many scripts (also including East-Asian scripts). Any fonts installed within the system would automatically used. Since Google intended to use Noto fonts to replace Droid Serif and (includingDroidSansFallback Roboto 

> Since Nimbus fonts is already included in DV font pack, this modifing is necessary.

Now both DV and DV font pack has included Nimbus fonts within apps. Nimbus fonts should be available only if DV font pack installed them.

**Comment by ericwa** [comment]
> Nimbus fonts should be available only if DV font pack installed them.

mupdf is using Nimbus fonts for the PDF base 14 fonts, which means they are needed to display PDF's.
So, this isn't really an option: they need to be in the main apk. Also, mupdf isn't designed to compile without the Nimbus fonts, afaik.

Based on @abderrahim 's comment I would say trying to load system copies of fonts is not worth it. imho, it's like using an undocumented API, there is no guarantee in the Android docs that the fonts will be there or what will be inside, so we should avoid it.

While working on my PR for mupdf 1.9a I recorded some sizes for different build configs:
size of document-viewer-armeabi-v7a-debug.apk:
mupdf 1.9a, default config: 11787194 bytes
mupdf 1.9a, -DNOCJK: 8124808 bytes
mupdf 1.9a, -DNOCJK, -DTOFU: 4090973 bytes (-DTOFU disables embedding noto fonts)
mupdf 1.7: 3930115 bytes

Also worth noting, mupdf 1.9 does complex script layout for epub now.

**Comment by KrasnayaPloshchad** [comment]
I have heard MuPDF 1.11 is allowed to use system fonts, does it helpful?

**Comment by ericwa** [comment]
Fixed by 4fd2c5fb59a71599ffddcbf5355ec0ac3327d66f - this enables DroidSansFallback which has some CJK support.
We're still disabling "Source Han Sans per-language fonts" and "DroidSansFallbackFull" - these ones are really large. Also disabling Noto (also large).

I haven't looked into how MuPDF 1.11 is using system fonts, or if this can be of any use to us.
