### ISSUE TITLE
move /sdcard/.org.sufficientlysecure.viewer to /sdcard/Android/data/org.sufficientlysecure.viewer

### ISSUE THREAD

**Issue by yuphorian6** [PrivacyApps/document-viewer#125]
Please move /sdcard/.org.sufficientlysecure.viewer to /sdcard/Android/data/org.sufficientlysecure.viewer 

Also gets rid of WRITE_EXTERNAL_STORAGE permission.

**Comment by ericwa** [comment]
Fixed in 776c1e5e02b41b91ba5e88f5ccc066d9e881d1ac
