### ISSUE TITLE
Require API 14?

### ISSUE THREAD

**Issue by ericwa** [PrivacyApps/document-viewer#249]
Support library 26.0.0 is going to require API 14 (Android 4.0, released Oct 2011).
Also, we need to require API 14 if we use https://github.com/mikepenz/MaterialDrawer

@dschuermann if it's easy to check, does the Google Play developer console show how many DV users are on API 13 or less (Android 3.x or earlier)?

**Comment by dschuermann** [comment]
yup, here are the stats:

![untitled](https://cloud.githubusercontent.com/assets/321888/26049467/ca16218c-3963-11e7-8c19-26b771b18b42.png)

**Comment by ericwa** [comment]
Ok - this is done in 6371f4ad0f784c3d8aec4bf1d8b19c95535902ce
