### ISSUE TITLE
Cannot install App on arm64 / Android7.1.2 / LineageOS 14.1

### ISSUE THREAD

**Issue by c33s** [PrivacyApps/document-viewer#260]
- Tablet: Samsung Galaxy Tab S2 - SM-813
- OS: LinageOS 14.1 (Android 7.1.2)

```
App not installed.
This app isn't compatible with your tablet.
```

is this because of arm64? shouldn't arm64 be fully backwards compatible? is this an error in the app or in the os?
even my aLogcat has an error (`/data/app/org.jtb.alogcat-1/lib/arm64`).

**Comment by ericwa** [comment]
That's strange. I don't have an arm64 device but I'll try installing an arm64-v8a emulator image.

Did you get the APK from f-droid or another source?

**Comment by ericwa** [comment]
Hm.. I tried to install https://f-droid.org/repo/org.sufficientlysecure.viewer_2797.apk
on an Android 7.1.1 arm64-v8a emulator and got this:
```
$ adb install ~/Downloads/org.sufficientlysecure.viewer_2797.apk 
Failed to install /Users/ericwa/Downloads/org.sufficientlysecure.viewer_2797.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

**Comment by c33s** [comment]
@ericwa sorry for the late reply, i havn't seen a notification that you commented here. yes the apk is from f-droid.org

i reproduced the error on the orginal samsung rom  Android 7.0, so it is nothing lineageos specific.

currently `adb` is not working for me, i have to investigate the problem (think it is a usb driver problem)

**Comment by c33s** [comment]
```
λ adb install org.sufficientlysecure.viewer_2797.apk
9619 KB/s (6777168 bytes in 0.688s)
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```
same result as in the emulator.

if i can help with testing just tell.

**Comment by ericwa** [comment]
@c33s Oops, I made a mistake - 2797 is the mips64 apk!

This one is the arm64 apk, and it installs on my emulator and works:
https://f-droid.org/repo/org.sufficientlysecure.viewer_2795.apk

Does that one work for you? Does the F-droid gui pick the wrong APK?

**Comment by c33s** [comment]
this solves the problem. thank you for your support.

how to know which one to download if you don't use the fdroid app? the page doesn't show for which processor it was build.

https://f-droid.org/packages/org.sufficientlysecure.viewer/

![2017-10-20 11_45_15- document viewer _ f-droid - free and open source android app repository](https://user-images.githubusercontent.com/649209/31815180-3e5d9364-b58c-11e7-870d-6c3d3e6b32b1.png)

should fdroid add the supported processor types to the page or is it possible for you to build apks which support all processors?

**Comment by c33s** [comment]
@ericwa
>how to know which one to download if you don't use the fdroid app? the page doesn't show for which >processor it was build.

**Comment by ericwa** [comment]
Sorry - I'm not sure how to make the fdroid web page list which ABI corresponded to which version code.
I install DV with the fdroid app which will pick the correct ABI.. but agree it would be good to have it listed on the download page.
