### ISSUE TITLE
Fails to display Japanese characters

### ISSUE THREAD

**Issue by ShapeShifter499** [PrivacyApps/document-viewer#264]
I'm currently taking Japanese language classes and because of this I'm accessing a lot of PDF files that contain Japanese characters. Some of these do not display properly or at all with document-viewer on LineageOS 14.1 (Android 7.1.2). Are there any font packs I can get? Or any fixes? Or any plans to add support?

**Comment by ericwa** [comment]
We are disabling some CJK font options when compiling mupdf:
https://github.com/PrivacyApps/document-viewer/blob/master/document-viewer/jni/mupdf/Core.mk#L15
so right now, I think Japanese only works if the fonts are embedded in the pdf.

Unfortunately the font pack support has bitrotted and no longer works. 

Changing the compile flags so we build with more fonts included sounds good to me. It would also allow reading epub's that use non-latin alphabets.

For now, maybe the official mupdf app is compiled with all fonts, and can read these pdf's?
https://f-droid.org/packages/com.artifex.mupdfdemo/

**Comment by ShapeShifter499** [comment]
I didn't know about the MuPDF app before today. Seems like Japanese characters displays properly in MuPDF from what I could tell.  Can I ask, are there any major downsides (aside from font support) between document-viewer and MuPDF?

**Comment by ericwa** [comment]
Good to hear it works in mupdf.
It should be possible to fix the display of these pdf's in document-viewer by tweaking the compile flags we use, then. If they're not publically available PDF's, would it be possible to email me one that is displaying incorrectly document-viewer, just to use as a test case?

Aside from the font issue, both apps use the same library underneath (mupdf) so the differences are just in the UI and what features are exposed. The mupdf app has annotations, text selection, reflow. DV has auto crop, table of contents / outline, night mode / tint, more scrolling options (horizontal/vertical), book settings saved in a database, etc.

**Comment by ShapeShifter499** [comment]
I was trying to view a few of the kanji lists at http://www.csus.edu/indiv/s/sheaa/projects/genki/kanji_main.html   website is for learning some Japanese, rest of the site is in English. The PDFs are at the bottom, these are some of the PDFs that had issues displaying.

**Comment by ericwa** [comment]
Thanks , this works as a test case: http://www.csus.edu/indiv/s/sheaa/projects/genki/kanji/kanji03_ws.pdf

**Comment by ericwa** [comment]
This is fixed in 4fd2c5fb59a71599ffddcbf5355ec0ac3327d66f
