### ISSUE TITLE
MuPDF vulnerabilities

### ISSUE THREAD

**Issue by mimi89999** [PrivacyApps/document-viewer#266]
https://gitlab.com/fdroid/fdroiddata/issues/956

Please update to the latest version of the lib and make an new release.

**Comment by ericwa** [comment]
Thanks. Should be fixed in 0bfb13b1b65cc27145b4526a3c2564ecdb468674
I'll tag a release today

**Comment by mimi89999** [comment]
Thanks

**Comment by ericwa** [comment]
2.8.0 is available in fdroid, which has these patches.

**Comment by mimi89999** [comment]
Yes. Finally we have them. One build has failed tho: https://f-droid.org/wiki/page/org.sufficientlysecure.viewer/lastbuild_2801
