### ISSUE TITLE
F-Droid builds failing

### ISSUE THREAD

**Issue by sm400** [PrivacyApps/document-viewer#268]
F-Droid builds have been failing since version 2801. See https://f-droid.org/wiki/page/org.sufficientlysecure.viewer

**Comment by ericwa** [comment]
Yes, it's some kind of problem with fdroid server cleaning up it's git checkout.
There is an fdroid server issue about the problem: https://gitlab.com/fdroid/fdroidserver/issues/381
I'm not sure if there is anything we can do.

**Comment by ericwa** [comment]
It's fixed now and 2.8.0 is available in fdroid
