### ISSUE TITLE
changed directory and effects on fontpack

### ISSUE THREAD

**Issue by DJCrashdummy** [PrivacyApps/document-viewer#271]
according to the [changelog](https://github.com/PrivacyApps/document-viewer/blob/master/document-viewer/src/main/assets/about/en/changelog.wiki#DV_v280) `/sdcard/.org.sufficientlysecure.viewer` is (thankfully) not created anymore... what does this mean for and is something similar also planed with the [DV fontpack](https://github.com/PrivacyApps/document-viewer-fontpack)?
- while running it `/sdcard/.org.sufficientlysecure.viewer.fontpack` is still created, just for the logs
- the fonts are "installed" into `/sdcard/.org.sufficientlysecure.viewer`, so this folder will still be needed... and does the new versions of DV even look for the fonts at this place?

thanks for some clarification!

**Comment by ericwa** [comment]
Sorry for not documenting this better, but the font pack feature is no longer working for the last couple of releases.
I thought the benefits of upgrading mupdf (steadily improving EPUB rendering) outweighed the loss of the fontpack (which only ever worked with the FB2 renderer. That's now gone and we're using mupdf to render FB2 documents.). We were patching mupdf to make it load the font pack, but the patch no longer applies to recent mupdf versions and I'm not sure if it ever worked in the first place.

What I do want to add is font control for FB2 and EPUB documents; it's possible with mupdf and shouldn't be too difficult.

**Comment by DJCrashdummy** [comment]
thank you very much @ericwa for the clarification!

maybe some words in the readme of the fontpack would be a good idea.

**Comment by DJCrashdummy** [comment]
and also the still available section in the readme (https://github.com/PrivacyApps/document-viewer#font-pack) leaves a wrong impression.

**Comment by ericwa** [comment]
Thanks for the reminder, the readme is now updated.
