### ISSUE TITLE
Add EPUB support to F-Droid description

### ISSUE THREAD

**Issue by obar** [PrivacyApps/document-viewer#278]
Right now an F-Droid search for 'ebook' or 'epub' doesn't return this app as a result, but it should. [The description](https://f-droid.org/packages/org.sufficientlysecure.viewer/) should be updated to match.

**Comment by ericwa** [comment]
Opened a merge request: https://gitlab.com/fdroid/fdroiddata/merge_requests/2787

**Comment by ericwa** [comment]
It's updated now, thanks for the reminder!
