### ISSUE TITLE
PDF not well rendered

### ISSUE THREAD

**Issue by ineff** [PrivacyApps/document-viewer#280]
I am ha ing trouble to render the following pdf https://arxiv.org/pdf/1801.10542.pdf

The viewer seems to be unable to render the first page.

The problem does not affect Google pdf viewer nor any other Desktop application.

**Comment by ericwa** [comment]
first page displays OK for me in v2.8.1

**Comment by ineff** [comment]
Is there any way I can find the apk of the new version? I am stuck with 2.7.9 and would prefer not having to compile.

**Comment by ericwa** [comment]
Preferred way is to install document-viewer from fdroid:
https://f-droid.org/en/packages/org.sufficientlysecure.viewer/

(If you want to download the APK directly they're not labelled clearly, unfortunately, 2812 = armeabi-v7a is probably the most common abi?)

**Comment by ineff** [comment]
Thanks. Probably the problem was due to some incompatibility with the older versions. The update fixed it.
