### ISSUE TITLE
v2.8.0 and newer crash Launcher,App List etc. on some ROMs

### ISSUE THREAD

**Issue by hre999** [PrivacyApps/document-viewer#281]
It seems to be a common issue with getPkgName on OEM and custom ROMs:
https://issuetracker.google.com/issues/64434571
https://gitlab.com/fdroid/fdroiddata/issues/979

In short: Starting with the Gradle Android-Plugin 3.0.0 aapt2 will be used for packaging. Some ROMS don't copy a buffer in getPkgName, which with aapt is fine, with aapt2 will produce crashes.

Actually a bug with the ROMs, but its easily fixed with adding `android.enableAapt2=false` to _grade.properties_ or using build tools >=27 (the latter I did not test though)

**Comment by ericwa** [comment]
See also: https://github.com/PrivacyApps/document-viewer/issues/273

The summary is: we made a 2.8.1 release with the build tools 27 workaround, but it's not available in f-droid due to an f-droid issue: https://gitlab.com/fdroid/fdroidserver/issues/381

**Comment by ericwa** [comment]
@hre999 v2.8.1 is now available in f-droid which should have this fixed

**Comment by hre999** [comment]
Works! Thanks for the fast fix.
